const API_KEY = process.env.REACT_APP_YT_API_KEY;

export const YOUTUBE_LINK = `https://youtube.googleapis.com/youtube/v3/videos?part=snippet,contentDetails,statistics&chart=mostPopular&maxResults=49&regionCode=IN&key=${API_KEY}`;

export const YOUTUBE_SEARCH_API = "/api/suggest?q=";

const nameList = [
  "Aarav",
  "Vivaan",
  "Aditya",
  "Vihaan",
  "Arjun",
  "Sai",
  "Krishna",
  "Ishaan",
  "Rohan",
  "Kabir",
  "Ananya",
  "Diya",
  "Isha",
  "Aadhya",
  "Saanvi",
  "Priya",
  "Kavya",
  "Ritika",
  "Meera",
  "Nisha",
  "Raj",
  "Rahul",
  "Amit",
  "Suresh",
  "Vikram",
  "Sanjay",
  "Ravi",
  "Sunil",
  "Karan",
  "Manoj",
  "Pooja",
  "Neha",
  "Shruti",
  "Sonal",
  "Radhika",
  "Lakshmi",
  "Deepa",
  "Anjali",
  "Divya",
  "Jyoti",
  "Ganesh",
  "Shiva",
  "Omkar",
  "Pranav",
  "Harsh",
  "Alok",
  "Mohan",
  "Dinesh",
  "Nikhil",
  "Yash",
  "Chaitanya",
  "Siddharth",
  "Sameer",
  "Akhil",
  "Abhishek",
  "Tanvi",
  "Swara",
  "Aarohi",
  "Ira",
  "Navya",
  "Sanvi",
  "Pihu",
  "Avni",
  "Kaira",
  "Tara",
];

export const generateRandomName = () => {
  return nameList[Math.floor(Math.random() * nameList.length)];
};
const commentList = [
  "bro this gameplay is insane, can’t believe what just happened 😂",
  "omg I am literally screaming rn, this is peak content 😳🔥",
  "lol I was not expecting that at all, wtf 🤯",
  "gg ez bro, absolute unit of a player 👏",
  "this is so funny I can’t stop laughing 😂🤣",
  "wait wait wait, did that just actually happen? 😱",
  "ok this part is straight-up wild fr, I can’t deal 😎",
  "yooo the chat is going crazy over this moment 🤣",
  "lowkey obsessed with how this turned out, legit amazing 😍",
  "sheesh, someone clip that, this is insane 😤",
  "deadass tho, this is one of the best streams I’ve seen",
  "omfg stoppp, I’m dying here, too good 😂",
  "big mood, this is literally what I needed today",
  "rip me, I did not expect that at all 😢",
  "not gonna lie, I was shook when that happened 😳",
  "fr fr, this content slaps so hard 🔥🔥",
  "mood af, can’t relate more to this rn 😂",
  "ok boomer moment but I actually enjoyed that 😂",
  "literally screaming in my room, this is too much 🤣",
  "chat is chaotic and I love it, can’t stop watching 😎",
];
export const generateRandomComment = () => {
  return commentList[Math.floor(Math.random() * commentList.length)];
};
